# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-17 09:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20171017_1511'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='resLocations',
            new_name='restaurantLocations',
        ),
    ]
