# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-19 11:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0004_auto_20171019_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurantlocations',
            old_name='timestamp',
            new_name='created',
        ),
    ]
