# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-01 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0005_auto_20171019_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantlocations',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
